<definitions
    targetNamespace="http://www.sun.com/jbi/examples/sample-service/echo"
    name="echo"
    xmlns:tns="http://www.sun.com/jbi/examples/sample-service/echo"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    
    <types>
        <xsd:schema targetNamespace="http://www.sun.com/jbi/examples/sample-service/echo">
            <xsd:element name="item">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element type="xsd:string" name="value"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>
    
    <message name="echo">
        <part name="part"
              element="tns:item">
        </part>
    </message>
    
    <portType name="echo">
        <operation name="echo">
            <input message="tns:echo"></input>
            <output message="tns:echo"></output>
        </operation>
    </portType>
    
    <binding name="Binding" type="tns:echo">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="echo">
            <soap:operation soapAction="echo"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    
    <service name="echoService">
        <port name="port" binding="tns:Binding">
            <soap:address location="http://localhost:12010/inetBanking_v2/echo"/>
        </port>
    </service>
    
</definitions>
